name: Bug Report
description: Capture regressions with clear contracts and acceptance.
title: "B-<slug>: "
labels:
  - lane:bug
body:
  - type: input
    id: bug_id
    attributes:
      label: Bug ID
      description: Use the `B-<slug>` format so the fix and PR stay linked.
      placeholder: B-hotkey-mismatch
    validations:
      required: true
  - type: dropdown
    id: lane
    attributes:
      label: Lane
      description: Which lane owns the fix and rollout?
      options:
        - A
        - B
        - C
        - D
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Current Behavior
      description: Describe what broke and the invariant it violates.
      placeholder: |
        Expected: keyboard shortcut submits form.
        Actual: shortcut triggers twice, causing double submission.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: Step-by-step reproduction with environment notes.
      placeholder: |
        1. Visit /editor with feature flag `inline-edit` enabled.
        2. Focus title field and press Cmd+Enter.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Checklist
      description: Track completion as `- [ ] item` so the PR inherits verification.
      placeholder: |
        - [ ] Shortcut fires once per activation
        - [ ] Regression test covers command palette use
        - [ ] Rollout plan includes monitoring for duplicate events
    validations:
      required: true
