name: Composition Ticket
description: Orchestrate the rollout plan across multiple Units.
title: "C-<slug>: "
labels:
  - lane:composition
body:
  - type: input
    id: composition_id
    attributes:
      label: Composition ID
      description: Use the `C-<slug>` format so linked Units and PRs stay aligned.
      placeholder: C-onboarding-handoff
    validations:
      required: true
  - type: dropdown
    id: lane
    attributes:
      label: Lane
      description: Which lane stewards this composition through rollout?
      options:
        - A
        - B
        - C
        - D
    validations:
      required: true
  - type: textarea
    id: units
    attributes:
      label: Units In Scope
      description: List every `U-<slug>` with owner and dependency contract.
      placeholder: |
        - `U-inline-edit` — D owns implementation, A validates data feeds
        - `U-review-banner` — B rolls out copy, C handles tracking hooks
    validations:
      required: true
  - type: textarea
    id: metric
    attributes:
      label: Metric Hypothesis
      description: State the invariant you expect to move and how you will measure it.
      placeholder: |
        Hypothesis: Composition reduces onboarding time by 15%.
        Measurement: Funnel step timestamps in `onboarding_flow_completed`.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Checklist
      description: Track completion as `- [ ] item` so rollout status is portable.
      placeholder: |
        - [ ] All Units in scope shipped behind guard
        - [ ] Contracts reviewed with analytics
        - [ ] Rollout playbook updated with fallback plan
    validations:
      required: true
