blank_issues_enabled: false
contact_links:
  - name: Project Contracts
    url: https://github.com/orgs/plaincraft/projects
    about: Check the Plaincraft Roadmap for lane ownership and rollout invariants.
