name: Unit Ticket
description: Capture the contracts and rollout invariants for a single Unit.
title: "U-<slug>: "
labels:
  - lane:unit
body:
  - type: input
    id: unit_id
    attributes:
      label: Unit ID
      description: Use the `U-<slug>` format so commits and PRs stay linked.
      placeholder: U-inline-edit
    validations:
      required: true
  - type: dropdown
    id: lane
    attributes:
      label: Lane
      description: Which lane owns this Unit through rollout?
      options:
        - A
        - B
        - C
        - D
    validations:
      required: true
  - type: textarea
    id: props
    attributes:
      label: Props + Shape
      description: List required props, defaults, and any contracts for consumption.
      placeholder: |
        - prop: `title` (string, required) — aligns heading levels with docs
        - prop: `ctaLabel` (string, optional) — defaults to "Continue"
    validations:
      required: true
  - type: textarea
    id: behaviors
    attributes:
      label: Behaviors
      description: Describe the invariants for interactions and data mutations.
      placeholder: |
        - On submit, emit `onComplete` exactly once.
        - Loading state masks actions until `onComplete` resolves.
    validations:
      required: true
  - type: textarea
    id: accessibility
    attributes:
      label: Accessibility
      description: Note focus order, keyboard affordances, aria contracts.
      placeholder: |
        - Primary CTA gets initial focus on mount.
        - Aria-live region announces validation errors inline.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Checklist
      description: Track completion as `- [ ] item` so PR checklists inherit.
      placeholder: |
        - [ ] Storybook story documents props
        - [ ] Unit README updated with rollout notes
        - [ ] Contracts verified with integration partner
    validations:
      required: true
