name: ci

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm format:check
      - run: pnpm typecheck
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm build
      - name: Build Storybook
        run: pnpm build:storybook
      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: Serve Storybook static build
        run: |
          pnpm dlx http-server storybook-static --port 6006 --host 127.0.0.1 --silent &
          echo "STORYBOOK_SERVER_PID=$!" >> $GITHUB_ENV
      - name: Wait for Storybook
        run: pnpm dlx wait-on http://127.0.0.1:6006
      - name: Run Storybook tests
        run: pnpm storybook:test -- --url http://127.0.0.1:6006
      - name: Stop Storybook server
        if: always()
        run: kill $STORYBOOK_SERVER_PID
